Feature/261951 regulator review download api
DEFRA/epr-pom-api-submission-status pull request #1
Opened 2024-05-17 06:16 UTC by nadir2khanexternal

2024-05-21 08:24 UTC, scdefra approved these changes

2024-05-21 08:25 UTC, JawwadBaigEviden submitted a review, later dismissed

2024-05-28 10:51 UTC, EvidenPete submitted a review, later dismissed

2024-05-28 12:20 UTC, scdefra approved these changes

2024-05-28 12:42 UTC, scdefra requested changes
We need some CommandValidator tests for the new FileDownloadCheckEventCreateCommandValidator

These files need some code coverage:

https://vss-sonarqube.azure.defra.cloud/component_measures?id=epr-pom-api-submission-status&metric=new_coverage&pullRequest=1&view=list

2024-05-28 15:06 UTC, scdefra approved these changes

2024-05-28 15:25 UTC, EvidenPete approved these changes

2024-05-28 15:25 UTC, merged

2024-05-28 15:25 UTC, JawwadBaigEviden approved these changes