Feature/453827 organisation registration decision handling
DEFRA/epr-pom-api-submission-status pull request #7
Opened 2024-11-06 18:04 UTC by JulianYoungEviden

### Support Regulator Organisation Registration Decision Submission Events
This change allows creating a new event in the SubmissionEvents container.
A new EventType has been added, RegulatorOrganisationRegistratioDecision, with value 12.  This is because it cannot overload the existing RegulatorDecision as that is for submissions with Files.
Save and Get operations exist, with the Get command support a SubmissionID filter.
The Swagger UI has been specified to present a meaningful test datum.

2024-11-07 08:53 UTC, johnfitzgeraldEviden approved these changes, later dismissed

2024-11-07 09:16 UTC, shehzad-ismail8 approved these changes, later dismissed

2024-11-07 14:14 UTC, shehzad-ismail8 requested changes
A couple of comments

2024-11-07 14:14 UTC, shehzad-ismail8 commented on src/EPR.SubmissionMicroservice.Application.UnitTests/Features/Commands/SubmissionEventCreate/Validators/RegulatorOrganisationRegistrationDecisionCreateCommandValidatorTests.cs
> +        //result.ShouldHaveValidationErrorFor(x => x.SubmissionId)
Are these comments required?

2024-11-07 14:14 UTC, shehzad-ismail8 commented on src/EPR.SubmissionMicroservice.Application/Features/Commands/SubmissionEventCreate/Validators/RegulatorOrganisationRegistrationDecisionEventCreateCommandValidator.cs
> +        //Include(new SubmissionEventCreateCommandValidator(queryRepository));
Is this comment required?

2024-11-07 14:18 UTC, JulianYoungEviden commented on src/EPR.SubmissionMicroservice.Application.UnitTests/Features/Commands/SubmissionEventCreate/Validators/RegulatorOrganisationRegistrationDecisionCreateCommandValidatorTests.cs
> +        //result.ShouldHaveValidationErrorFor(x => x.SubmissionId)
The code will be reverted I expect

2024-11-07 14:18 UTC, JulianYoungEviden commented on src/EPR.SubmissionMicroservice.Application/Features/Commands/SubmissionEventCreate/Validators/RegulatorOrganisationRegistrationDecisionEventCreateCommandValidator.cs
> +        //Include(new SubmissionEventCreateCommandValidator(queryRepository));
The code will be reverted I expect

2024-11-07 14:20 UTC, shehzad-ismail8 commented on src/EPR.SubmissionMicroservice.Application.UnitTests/Features/Commands/SubmissionEventCreate/Validators/RegulatorOrganisationRegistrationDecisionCreateCommandValidatorTests.cs
> +        //result.ShouldHaveValidationErrorFor(x => x.SubmissionId)
Okay

2024-11-07 14:20 UTC, shehzad-ismail8 commented on src/EPR.SubmissionMicroservice.Application/Features/Commands/SubmissionEventCreate/Validators/RegulatorOrganisationRegistrationDecisionEventCreateCommandValidator.cs
> +        //Include(new SubmissionEventCreateCommandValidator(queryRepository));
Okay

2024-11-07 14:21 UTC, shehzad-ismail8 approved these changes, later dismissed

2024-11-07 14:24 UTC, johnfitzgeraldEviden submitted a review, later dismissed

2024-11-13 16:37 UTC, shehzad-ismail8 approved these changes

2024-11-13 16:38 UTC, johnfitzgeraldEviden approved these changes

2024-11-13 17:22 UTC, MasilEviden approved these changes

2024-11-13 17:24 UTC, merged